# Generated by Django 4.2.1 on 2023-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256)),
                (
                    "filetype",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        max_length=5,
                    ),
                ),
                ("file", models.FileField(upload_to="%Y/%m/%d")),
                ("downloads", models.IntegerField(default=0)),
                ("emails", models.IntegerField(default=0)),
            ],
        ),
    ]
